connectionString: Endpoint=sb://cn-ins-eventhubnamespcae-002-d.servicebus.chinacloudapi.cn/;SharedAccessKeyName=SendPolicy;SharedAccessKey=Xs8UPHCUiTqy/XEbg8ITwvK2GM4imUfxcYDYFqbhB60=
eventHubName: oip_integration_mds_test
consumerGroup: test